name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start app in background
        run: |
          nohup python main.py > server.log 2>&1 &
          echo "Server started in background"
          sleep 5  # wait a few seconds for server startup

      - name: Run tests
        run: |
          python -m pytest test_main.py -v

      - name: Stop app
        if: always()
        run: |
          pkill -f "python main.py" || true
          echo "Server stopped"
